package com.luminn.firebase.entity;

/**
 * Created by hrlum on 22.03.2017.
 */
public enum RIDESTATUS {
    RESERVED,ACCEPTED,REJECT,CHANGE,CANCEL,CANCEL_BOOKING,FINISH,PRECANCEL_BY_USER,PRECANCEL_BY_DRIVER,
    REQUEST_CHANGEDESTINATION,RIDE_CANCEL_BOOKING,RIDE_REQUEST_CHANGEDESTINATION,
    DRIVER_CANCEL_RIDE,RIDE_START,RIDE_FINISH,RIDE_SUBMITTED,CANCEL_BY_USER,CANCEL_BY_DRIVER,RIDE_ON
}
